apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: vyxfiuyu-go 
  janus-idp.io/tekton: vyxfiuyu-go
  backstage.io/kubernetes-id: vyxfiuyu-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: vyxfiuyu-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml